#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108010014-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : LICENSE.md
# @ReadME        : aliases --help
# @Copyright     : Copyright: (c) 2022 Jason Hempstead, Casjays Developments
# @Created       : Sunday, Jan 23, 2022 22:21 EST
# @File          : aliases
# @Description   :
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[ -f "$(builtin type -P myscreen 2>/dev/null)" ] && [ -f "$(builtin type -P screen 2>/dev/null)" ] && alias screen='myscreen ' || alias screen='screen -t default '
[ -f "$HOME/.config/screen/dev/sshrc" ] && [ -f "$(builtin type -P screen 2>/dev/null)" ] && alias screen-ssh='screen -c $HOME/.config/screen/dev/sshrc ' || alias screen-ssh='screen -t ssh '
[ -f "$HOME/.config/screen/singlerc" ] && [ -f "$(builtin type -P screen 2>/dev/null)" ] && alias screen-single='screen -c $HOME/.config/screen/singlerc ' || alias screen-single='screen -t single '
[ -f "$HOME/.config/screen/dev/noderc" ] && [ -f "$(builtin type -P screen 2>/dev/null)" ] && alias screen-node='screen -c $HOME/.config/screen/dev/noderc ' || alias screen-node='screen -t node '
[ -f "$HOME/.config/screen/productivityrc" ] && [ -f "$(builtin type -P screen 2>/dev/null)" ] && alias screen-prod='screen -c $HOME/.config/screen/productivityrc ' || alias screen-single='screen -t prod '
[ -f "$HOME/.config/screen/other/socialrc" ] && [ -f "$(builtin type -P screen 2>/dev/null)" ] && alias screen-social='screen -c $HOME/.config/screen/other/socialrc ' || alias screen-social='screen -t social '
[ -f "$HOME/.config/screen/dev/developmentrc" ] && [ -f "$(builtin type -P screen 2>/dev/null)" ] && alias screen-dev='screen -c $HOME/.config/screen/dev/developmentrc ' || alias screen-dev='screen -t dev '
